# Generated by Django 4.2.7 on 2023-11-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genotype')),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.phenotype')),
            ],
        ),
    ]
