# Generated by Django 4.2.7 on 2023-11-02 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('app', '0003_rename_genotype_common_gen_and_more'),
	]

	operations = [
		migrations.CreateModel(
			name='UserData',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('commons', models.ManyToManyField(to='app.common')),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
			],
		),
	]
