# Generated by Django 4.2.7 on 2024-01-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('app', '0004_userdata'),
	]

	operations = [
		migrations.CreateModel(
			name='PopulationFrequency',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(blank=True, max_length=255)),
				('locus', models.CharField(blank=True, max_length=255)),
				('chromosome', models.IntegerField(default=0)),
				('position', models.IntegerField(default=0)),
				('minor_allele_frequency', models.FloatField(default=0.0)),
				('minor_allele', models.CharField(blank=True, max_length=255)),
				('major_allele', models.CharField(blank=True, max_length=255)),
				('major_allele_frequency', models.FloatField(default=0.0)),
				('description', models.TextField(blank=True, default='')),
			],
		),
		migrations.AlterField(
			model_name='common',
			name='phen',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.populationfrequency'),
		),
		migrations.DeleteModel(
			name='Phenotype',
		),
	]
