# Generated by Django 4.2.7 on 2024-02-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('app', '0005_populationfrequency_alter_common_phen_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='common',
			name='gen',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commons_gen', to='app.genotype'),
		),
		migrations.AlterField(
			model_name='common',
			name='phen',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commons_phen', to='app.populationfrequency'),
		),
		migrations.AlterField(
			model_name='genotype',
			name='description',
			field=models.TextField(blank=True),
		),
		migrations.AlterField(
			model_name='populationfrequency',
			name='description',
			field=models.TextField(blank=True),
		),
		migrations.AlterField(
			model_name='userdata',
			name='commons',
			field=models.ManyToManyField(related_name='user_data', to='app.common'),
		),
	]
