# Generated by Django 4.2.7 on 2024-02-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_common_gen_alter_common_phen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common',
            name='gen',
        ),
        migrations.RemoveField(
            model_name='common',
            name='phen',
        ),
        migrations.AddField(
            model_name='common',
            name='population_frequency',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='commons_population_frequency', to='app.populationfrequency'),
        ),
    ]
