# Generated by Django 5.1.1 on 2025-10-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_inputquality_remove_samplegroup_time_stored_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bioinfoalignment",
            name="tool",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="platformindependent",
            name="instrument",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
