# Generated by Django 5.1.1 on 2025-10-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_allelefrequency_sample_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a260_a280", models.FloatField(blank=True, null=True)),
                ("a260_a230", models.FloatField(blank=True, null=True)),
                ("dna_concentration", models.FloatField(blank=True, null=True)),
                ("rna_concentration", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("additional_metrics", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="samplegroup",
            name="allele_frequency",
        ),
        migrations.AddField(
            model_name="allelefrequency",
            name="sample_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allele_frequencies",
                to="app.samplegroup",
            ),
        ),
        migrations.AddField(
            model_name="samplegroup",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="samplegroup",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="samplegroup",
            name="doi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="samplegroup",
            name="exclusion_criteria",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplegroup",
            name="inclusion_criteria",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplegroup",
            name="source_lab",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="samplegroup",
            name="total_samples",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplegroup",
            name="input_quality",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sample_group",
                to="app.inputquality",
            ),
        ),
    ]
