# Generated by Django 5.1.1 on 2025-10-08 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_assign_user(apps, schema_editor):
    SampleGroup = apps.get_model("app", "SampleGroup")
    OrganizationProfile = apps.get_model("app", "OrganizationProfile")

    profile_to_user = {
        profile.pk: profile.user_id for profile in OrganizationProfile.objects.all()
    }

    updates = []
    for sample_group in SampleGroup.objects.all():
        profile_id = sample_group.created_by_id
        user_id = profile_to_user.get(profile_id)
        if user_id is not None:
            sample_group.created_by_id = user_id
            updates.append(sample_group)

    for sample_group in updates:
        sample_group.save(update_fields=["created_by"])


def backwards_assign_profile(apps, schema_editor):
    SampleGroup = apps.get_model("app", "SampleGroup")
    OrganizationProfile = apps.get_model("app", "OrganizationProfile")

    user_to_profile = {
        profile.user_id: profile.pk for profile in OrganizationProfile.objects.all()
    }

    updates = []
    for sample_group in SampleGroup.objects.all():
        user_id = sample_group.created_by_id
        profile_id = user_to_profile.get(user_id)
        if profile_id is not None:
            sample_group.created_by_id = profile_id
            updates.append(sample_group)

    for sample_group in updates:
        sample_group.save(update_fields=["created_by"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_allelefrequency_sample_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplegroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards_assign_user, backwards_assign_profile),
    ]
