# Generated by Django 5.1.1 on 2025-10-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_inputquality_remove_samplegroup_allele_frequency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bioinfoalignment",
            name="software",
        ),
        migrations.RemoveField(
            model_name="samplegroup",
            name="collection_method",
        ),
        migrations.RemoveField(
            model_name="samplegroup",
            name="storage_conditions",
        ),
        migrations.RemoveField(
            model_name="samplegroup",
            name="tissue",
        ),
    ]
