# Generated by Django 5.1.1 on 2025-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_merge_20250304_0001"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformindependent",
            name="instrument",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
