# Generated by Django 5.1.1 on 2025-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_platformindependent_instrument"),
    ]