# Generated by Django 5.1.1 on 2025-10-08 15:13

from django.db import migrations


def _normalize(value):
    if value is None:
        return None
    if isinstance(value, str):
        stripped = value.strip()
        return stripped or None
    return value


def backfill_sample_origin(apps, schema_editor):
    SampleGroup = apps.get_model("app", "SampleGroup")
    SampleOrigin = apps.get_model("app", "SampleOrigin")

    for group in SampleGroup.objects.select_related("sample_origin"):
        tissue = _normalize(getattr(group, "tissue", None))
        collection = _normalize(getattr(group, "collection_method", None))
        storage = _normalize(getattr(group, "storage_conditions", None))

        if group.sample_origin_id is None:
            if not any([tissue, collection, storage]):
                continue
            origin = SampleOrigin.objects.create(
                tissue=tissue,
                collection_method=collection,
                storage_conditions=storage,
            )
            group.sample_origin = origin
            group.save(update_fields=["sample_origin"])
            continue

        origin = group.sample_origin
        updates = {}
        if tissue is not None:
            updates["tissue"] = tissue
        if collection is not None:
            updates["collection_method"] = collection
        if storage is not None:
            updates["storage_conditions"] = storage

        if updates:
            for field, value in updates.items():
                setattr(origin, field, value)
            origin.save(update_fields=list(updates.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_bioinfoalignment_tool"),
    ]

    operations = [
        migrations.RunPython(backfill_sample_origin, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="samplegroup",
            name="collection_method",
        ),
        migrations.RemoveField(
            model_name="samplegroup",
            name="storage_conditions",
        ),
        migrations.RemoveField(
            model_name="samplegroup",
            name="tissue",
        ),
    ]
