# Generated by Django 5.1.1 on 2025-10-08 15:30

from django.db import migrations, models


STRUCTURED_KEYS = [
    "ad",
    "adf",
    "adr",
    "dp",
    "ec",
    "ft",
    "gl",
    "gp",
    "gq",
    "gt",
    "hq",
    "mq",
    "pl",
    "pq",
    "ps",
]


def forwards(apps, schema_editor):
    Format = apps.get_model("app", "Format")
    for format_obj in Format.objects.all():
        fields_payload = {}
        for key in STRUCTURED_KEYS:
            value = getattr(format_obj, key, None)
            if value not in (None, ""):
                fields_payload[key] = value

        additional_payload = getattr(format_obj, "additional", None) or {}

        payload = {}
        if fields_payload:
            payload["fields"] = fields_payload
        if additional_payload:
            payload["additional"] = additional_payload

        format_obj.genotype = fields_payload.get("gt")
        format_obj.payload = payload or None
        format_obj.save(update_fields=["genotype", "payload"])


def backwards(apps, schema_editor):
    Format = apps.get_model("app", "Format")
    for format_obj in Format.objects.all():
        payload = format_obj.payload or {}
        fields_payload = payload.get("fields") or {}
        additional_payload = payload.get("additional") or None

        update_fields = list(STRUCTURED_KEYS) + ["additional"]
        for key in STRUCTURED_KEYS:
            setattr(format_obj, key, fields_payload.get(key))
        format_obj.additional = additional_payload
        format_obj.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_bioinfoalignment_tool"),
    ]

    operations = [
        migrations.AddField(
            model_name="format",
            name="genotype",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="format",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="format",
            name="ad",
        ),
        migrations.RemoveField(
            model_name="format",
            name="additional",
        ),
        migrations.RemoveField(
            model_name="format",
            name="adf",
        ),
        migrations.RemoveField(
            model_name="format",
            name="adr",
        ),
        migrations.RemoveField(
            model_name="format",
            name="dp",
        ),
        migrations.RemoveField(
            model_name="format",
            name="ec",
        ),
        migrations.RemoveField(
            model_name="format",
            name="ft",
        ),
        migrations.RemoveField(
            model_name="format",
            name="gl",
        ),
        migrations.RemoveField(
            model_name="format",
            name="gp",
        ),
        migrations.RemoveField(
            model_name="format",
            name="gq",
        ),
        migrations.RemoveField(
            model_name="format",
            name="gt",
        ),
        migrations.RemoveField(
            model_name="format",
            name="hq",
        ),
        migrations.RemoveField(
            model_name="format",
            name="mq",
        ),
        migrations.RemoveField(
            model_name="format",
            name="pl",
        ),
        migrations.RemoveField(
            model_name="format",
            name="pq",
        ),
        migrations.RemoveField(
            model_name="format",
            name="ps",
        ),
    ]
