# Generated by Django 5.1.1 on 2025-10-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_bioinfoalignment_software"),
        ("app", "0015_remove_format_ad_remove_format_additional_and_more"),
    ]

    operations = []
