# Generated by Django 5.1.1 on 2025-10-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_merge_20251008_1615"),
        ("app", "0016_merge_20251008_1621"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformindependent",
            name="instrument",
        ),
    ]
