# Generated by Django 5.1.1 on 2025-10-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_remove_platformindependent_instrument"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bioinfovariantcalling",
            old_name="tool",
            new_name="vc_tool",
        ),
    ]
