# Generated by Django 5.1.1 on 2025-10-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_rename_tool_bioinfovariantcalling_vc_tool"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bioinfoalignment",
            old_name="tool",
            new_name="ba_tool",
        ),
    ]
