# Generated by Django 5.1.1 on 2025-10-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_rename_tool_bioinfoalignment_ba_tool"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bioinfoalignment",
            old_name="ba_tool",
            new_name="tool",
        ),
        migrations.RenameField(
            model_name="bioinfovariantcalling",
            old_name="vc_tool",
            new_name="tool",
        ),
        migrations.AddField(
            model_name="platformindependent",
            name="instrument",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
