# Generated by Django 5.1.1 on 2025-10-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_merge_20251008_1615"),
        ("app", "0020_rename_ba_tool_bioinfoalignment_tool_and_more"),
    ]

    operations = []
