# Generated by Django 5.1.1 on 2025-10-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_merge_20251008_1814"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplegroup",
            name="additional_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
