# Generated by Django 5.1.1 on 2025-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_samplegroup_additional_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="fs",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="info",
            name="qd",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="info",
            name="sor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
