# Generated by Django 5.1.1 on 2025-10-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_samplegroup_additional_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samplegroup",
            name="platform_independent",
        ),
        migrations.DeleteModel(
            name="PlatformIndependent",
        ),
    ]
