# Generated by Django 5.1.1 on 2025-10-09 10:09

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_samplegroup_additional_metadata"),
    ]
