# Generated by Django 5.1.1 on 2025-10-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_allelefrequency_sample_group_and_more"),
        ("app", "0023_info_fs_info_qd_info_sor_alter_info_ac_alter_info_af_and_more"),
        ("app", "0023_remove_samplegroup_platform_independent_and_more"),
    ]

    operations = []
