# Generated by Django 5.1.1 on 2025-10-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_merge_20251009_1125"),
    ]

    operations = [
    
        
       
    ]
