# Generated by Django 5.1.1 on 2025-10-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_info_fs_info_qd_info_sor"),
        ("app", "0024_merge_20251009_1125"),
    ]

    operations = []
