# Generated by Django 5.1.1 on 2025-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_merge_20251009_1127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="fs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="qd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="sor",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
