# Generated by Django 5.1.1 on 2025-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_info_fs_info_qd_info_sor_alter_info_ac_alter_info_af_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="ac",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="af",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="an",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="dp",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="fs",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="mq",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="qd",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="sor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
