# Generated by Django 5.1.1 on 2025-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_info_ac_alter_info_af_alter_info_an_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplegroup",
            name="sequencing_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("illumina", "Illumina"),
                    ("ont", "ONT"),
                    ("pacbio", "PacBio"),
                    ("ion_torrent", "Ion Torrent"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
