# Generated by Django 5.1.1 on 2026-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_samplegroup_sequencing_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allelefrequency',
            name='alt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='allelefrequency',
            name='chrom',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='allelefrequency',
            name='ref',
            field=models.CharField(max_length=255),
        ),
    ]
