name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MetaGap/requirements.txt coverage

      - name: Run Django tests with coverage
        id: tests
        continue-on-error: true
        run: |
          set -o pipefail
          python -m coverage run manage.py test 2>&1 | tee test-output.log

      - name: Generate coverage reports and enforce thresholds
        if: always()
        run: |
          if [ ! -f MetaGap/.coverage ]; then
            echo "No coverage data generated" | tee coverage-summary.txt
            exit 1
          fi

          cd MetaGap
          coverage report --skip-empty | tee ../coverage-summary.txt
          coverage report --include="*/MetagapUserCode/*" --fail-under=75
          coverage report --include="*/app/*" --fail-under=80
          coverage xml -o ../coverage.xml

      - name: Annotate metadata warnings
        if: always()
        run: |
          if [ -f test-output.log ]; then
            while IFS= read -r line; do
              message="${line#*:}"
              if [ -z "$message" ]; then
                message="$line"
              fi
              echo "::warning::${message}" 
            done < <(grep -n "Unhandled metadata key" test-output.log || true)
          fi

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: django-test-artifacts
          path: |
            test-output.log
            coverage-summary.txt
            coverage.xml
          if-no-files-found: warn

      - name: Fail if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1
